platform :ios, '7.0'
pod 'AFNetworking', '~> 2.2'
pod 'PBWebViewController', '~> 0.1'
pod 'JASidePanels', '~> 1.3.2'
pod 'SDWebImage', '~> 3.5'
pod 'Reachability', '~> 3.1'
pod 'CocoaLumberjack', '~> 1.8'
pod 'MWPhotoBrowser', '~> 1.4'
